name: movies_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.0.2
  provider: ^6.0.2
  cupertino_icons: ^1.0.4
  json_serializable: ^6.1.6
  json_annotation: ^4.4.0
  get_it: ^7.2.0
  hive: ^2.1.0
  dio: ^4.0.6
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.0
  firebase_core: 1.15.0
  firebase_analytics: ^9.1.6
  firebase_auth: 3.3.15
  cloud_firestore: 3.1.13


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.10
  hive_generator: ^1.1.2

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

